### ISSUE TITLE
A faulty brick can crash MIA

### ISSUE THREAD

**Issue by JanWP** [populse/populse_mia#109]
**Describe the bug**
If there is a coding error in a brick and the brick crashes, MIA may crash.

**Generated error**
Depends on the error produced by the brick. For example:
```
Exception hooking in progress ...

Clean up before closing mia done ...

Traceback (most recent call last):
  File "/home/warnking/code/fmri_processing/python/populse_mia_2019/populse_mia/python/populse_mia/user_interface/pipeline_manager/pipeline_manager_tab.py", line 1581, in run
    study_config.run(pipeline, verbose=1)
  File "/home/warnking/.virtualenvs/populse_mia_2019/lib/python3.6/site-packages/capsul/study_config/study_config.py", line 414, in run
    verbose)
  File "/home/warnking/.virtualenvs/populse_mia_2019/lib/python3.6/site-packages/capsul/study_config/study_config.py", line 471, in _run
    **kwargs)
  File "/home/warnking/.virtualenvs/populse_mia_2019/lib/python3.6/site-packages/capsul/study_config/run.py", line 102, in run_process
    returncode = process_instance._run_process()
  File "/home/warnking/.virtualenvs/populse_mia_2019/lib/python3.6/site-packages/mia_processes-1.2.1-py3.6.egg/mia_processes/process_mia.py", line 36, in _run_process
    self.run_process_mia()
  File "/home/warnking/code/fmri_processing/python/populse_mia_2019/populse_mia/processes/aslpipeline/aslpipeline.py", line 564, in run_process_mia
    toto = self.does_not_exist
AttributeError: 'ASLDesignMatrixGeneration' object has no attribute 'does_not_exist'
QObject::~QObject: Timers cannot be stopped from another thread
Segmentation fault (core dumped)
```

**To Reproduce**
1. Open the code of any custom brick
2. At the beginning of the _run_process_mia_ method, add:
```
toto = self.does_not_exist
```
3. Run a pipeline with the brick

**Expected behavior**
MIA should not crash, catch the error and show a dialog to the user with information on the caught error.

**Desktop**
 - OS: Ubuntu 18.04
 - Populse_MIA version: 1.1.1
 - nipype version: 1.2.0
 - mia_processes version: 1.2.1

**Comment by servoz** [comment]
I totally agree, MIA should never crash. This is no Windows ...
To be discussed conceptually. It seems there are several ways to do it.
High priority in the "Prioritisation of issues to be resolved" Milestone

**Comment by M40V** [comment]
Fixed by @servoz with this [commit](https://github.com/populse/populse_mia/commit/df395b645342787eb2790e4099169b02f3834d01#diff-e936c375bb7d7594432cf607253b34cf). The _study_config_ of _RunWorker_ is runned inside a _try_.
