### ISSUE TITLE
problem with config when using spm standalone (capsulengine branch)

### ISSUE THREAD

**Issue by servoz** [populse/populse_mia#164]
Using capsulengine branch.

With smooth brick from mia_processes library.

With mia preferences at 
Use Matlab standalone checked
Matlab standalone path: /usr/local/MATLAB/MATLAB_Runtime/v95
Use SPM standalone checked
SPM standalone path: /usr/local/SPM/spm12_standalone

Initialisation step is stuck and no crash is observed (only thanks to a try statement).

the output observed :

```
init pipeline...
Completion...
Exception occurred in traits notification handler.
Please check the log file for details.
Exception occurred in traits notification handler for object: <capsul.study_config.study_config.StudyConfig object at 0x7f8376c450b0>, trait: use_nipype, old value: True, new value: <undefined>
Traceback (most recent call last):
  File "/home/econdami/.local/lib/python3.7/site-packages/traits/trait_notifiers.py", line 591, in _dispatch_change_event
    self.dispatch(handler, *args)
  File "/home/econdami/.local/lib/python3.7/site-packages/traits/trait_notifiers.py", line 553, in dispatch
    handler(*args)
  File "/data/Git_Projects/capsul/capsul/study_config/config_modules/nipype_config.py", line 96, in initialize_module
    + " script",
IndexError: list index out of range

Error during initialisation:  list index out of range
Traceback (most recent call last):
  File "/data/Git_Projects/populse_mia/python/populse_mia/user_interface/pipeline_manager/pipeline_manager_tab.py", line 913, in initialize
    self.test_init = self.init_pipeline()
  File "/data/Git_Projects/populse_mia/python/populse_mia/user_interface/pipeline_manager/pipeline_manager_tab.py", line 766, in init_pipeline
    self.complete_pipeline_parameters(pipeline)
  File "/data/Git_Projects/populse_mia/python/populse_mia/user_interface/pipeline_manager/pipeline_manager_tab.py", line 599, in complete_pipeline_parameters
    engine = self.get_capsul_engine()
  File "/data/Git_Projects/populse_mia/python/populse_mia/usMatlab standalone path: er_interface/pipeline_manager/pipeline_manager_tab.py", line 587, in get_capsul_engine
    return self.pipelineEditorTabs.get_capsul_engine()
  File "/data/Git_Projects/populse_mia/python/populse_mia/user_interface/pipeline_manager/pipeline_editor.py", line 1373, in get_capsul_engine
    engine.study_config.import_from_dict(empty_config, clear=True)
  File "/data/Git_Projects/soma-base/python/soma/controller/controller.py", line 395, in import_from_dict
    delattr(self, trait_name)
  File "/home/econdami/.local/lib/python3.7/site-packages/traits/trait_notifiers.py", line 545, in __call__
    self.notify_listener(self, object, trait_name, old, new)
  File "/home/econdami/.local/lib/python3.7/site-packages/traits/trait_notifiers.py", line 619, in _notify_method_listener
    object, trait_name, old, new, listener
  File "/home/econdami/.local/lib/python3.7/site-packages/traits/trait_notifiers.py", line 599, in _dispatch_change_event
    handle_exception(object, trait_name, old, new)Matlab standalone path: 
  File "/home/econdami/.local/lib/python3.7/site-packages/traits/trait_notifiers.py", line 180, in _handle_exception
    raise excp
  File "/home/econdami/.local/lib/python3.7/site-packages/traits/trait_notifiers.py", line 591, in _dispatch_change_event
    self.dispatch(handler, *args)
  File "/home/econdami/.local/lib/python3.7/site-packages/traits/trait_notifiers.py", line 553, in dispatch
    handler(*args)
  File "/data/Git_Projects/capsul/capsul/study_config/config_modules/nipype_config.py", line 96, in initialize_module
    + " script",
IndexError: list index out of range
```

By taking a look at the File "/data/Git_Projects/capsul/capsul/study_config/config_modules/nipype_config.py", line 96, in initialize_module we can see:
 spm.SPMCommand.set_mlab_paths(
                    matlab_cmd=self.study_config.spm_exec + " " \
                        + glob.glob(os.path.join(
                            self.study_config.spm_directory, 'mcr', 'v*'))[0] \
                        + " script",
                    use_mcr=True)

I don't understand why self.study_config.spm_directory is used? It would be something like study_config.matlab_directory ? there is not a total synchronisation beetwen mia preferences and study_config/capsulengine ? (the Matlab standalone path is well defined in mia preference.  Surprisingly, by clicking on Edit capsul config in the mia preferences, you can see everything is fine for spm but for matlab, I only see matlab_exec with the value for non-standalone matlab !)

**Comment by servoz** [comment]
just tested with spm not standalone with same problem

**Comment by servoz** [comment]
Sorry, I guess I was a little tired last night... 

I started again this morning and I don't see the issue anymore. It may be that my populse versions weren't up to date (although I didn't make a pull this morning ... well the main thing is that this issue doesn't seem to exist !!!)

 I close this ticket!
