### ISSUE TITLE
- old format database make a crash

### ISSUE THREAD

**Issue by denisri** [populse/populse_mia#170]
- old format database make a crash 
```
Traceback (most recent call last):
  File "/data/Git_Projects/populse_mia/python/populse_mia/user_interface/main_window.py", line 600, in open_recent_project
    self.switch_project(relative_path, name)
  File "/data/Git_Projects/populse_mia/python/populse_mia/user_interface/main_window.py", line 1007, in switch_project
    self.update_project(file_path)
  File "/data/Git_Projects/populse_mia/python/populse_mia/user_interface/main_window.py", line 1161, in update_project
    self.data_browser.table_data.update_table()  # Table updated
  File "/data/Git_Projects/populse_mia/python/populse_mia/user_interface/data_browser/data_browser.py", line 2284, in update_table
    self.fill_headers(take_tags_to_update)
  File "/data/Git_Projects/populse_mia/python/populse_mia/user_interface/data_browser/data_browser.py", line 1509, in fill_headers
    tags.remove(TAG_CHECKSUM)
ValueError: list.remove(x): x not in list
```
this is not a big problem, because we can assume that nobody have already started a serious calculation with populse_mia and we just have to create a new database in populse_db v2.0 format (very minor remark)

_Originally posted by @servoz in https://github.com/populse/populse_mia/pull/165#issuecomment-651784602_

**Comment by denisri** [comment]
Yes populse_db v2 database format is completely different from populse_db v1. They cannot be compatible. But it is somewhat possible to make a conversion tool. This tool would require both populse_db 1 and populse_db 2. It would be difficult to make both versions work in the same program (they are different branches of the same project, or we would need to install both under different module names). So we would need to have a first program to read the older database using v1, then write something in an "independent" format (json, yaml, or pickle), then we would need to switch to v2 branch, read back the "independent" files, and feed a v2 database from them. So it's a bit tricky.
Is it worth the effort ?

**Comment by servoz** [comment]
No, I don't think it's worth it.
I'd be really surprised if a user complained about not being able to read his old db file anymore ...
