### ISSUE TITLE
matlab config is not working in jobs

### ISSUE THREAD

**Issue by denisri** [populse/populse_mia#172]
I just done a [pull request in capsul  to fix this problem of loosing the sys.path for dev mode in populse_mia](https://github.com/populse/capsul/pull/167).
BUT, now this is the next crash at run time:
```
data/Git_Projects/soma-workflow/python/soma_workflow/client_types.py:307: UserWarning: import sys; sys.path = ['/data/Git_Projects/populse_mia/python', '/data/Git_Projects/capsul', '/data/Git_Projects/soma-base/python', '/data/Git_Projects/soma-workflow/python', '/data/Git_Projects/populse_db/python', '/data/Git_Projects/mia_processes/python', '/data/Git_Projects/populse_mia/python/populse_mia', '/usr/lib64/python37.zip', '/usr/lib64/python3.7', '/usr/lib64/python3.7/lib-dynload', '/home/econdami/.local/lib/python3.7/site-packages', '/home/econdami/.local/lib/python3.7/site-packages/scikit_image-0.15.0-py3.7-linux-x86_64.egg', '/home/econdami/.local/lib/python3.7/site-packages/etelemetry-0.2.0-py3.7.egg', '/home/econdami/.local/lib/python3.7/site-packages/ci_info-0.1.1-py3.7.egg', '/home/econdami/.local/lib/python3.7/site-packages/six-1.14.0-py3.7.egg', '/home/econdami/.local/lib/python3.7/site-packages/rdflib-5.0.0-py3.7.egg', '/home/econdami/.local/lib/python3.7/site-packages/sip-5.0.1-py3.7-linux-x86_64.egg', '/home/econdami/.local/lib/python3.7/site-packages/nipype-1.6.0.dev0+ge1ea1980c-py3.7.egg', '/home/econdami/.local/lib/python3.7/site-packages/csv2report-0.1.0-py3.7.egg', '/usr/lib64/python3.7/site-packages', '/usr/lib/python3.7/site-packages', '/data/Git_Projects/populse_mia/processes']; from capsul.api import Process; Process.run_from_commandline("mia_processes.preprocess.spm.spatial_preprocessing.Smooth") contains single quote. It could fail using DRMAA
  % command_elem, UserWarning)
soma-workflow starting in light mode
Workflow controller initialised

 When the pipeline was launched, the following exception was raised: Error during workflow execution. Status=('finished_regularly', 1, None, None).
The workflow has not been removed from soma_workflow and must be deleted manually. 
Failed jobs: [42]
Aborted/killed jobs: []
============================================
---- failed job info ---
* job: 42: smooth1
* exit status: finished_regularly
* commandline:
'python3' '-c' 'import sys; sys.path = [\'/data/Git_Projects/populse_mia/python\', \'/data/Git_Projects/capsul\', \'/data/Git_Projects/soma-base/python\', \'/data/Git_Projects/soma-workflow/python\', \'/data/Git_Projects/populse_db/python\', \'/data/Git_Projects/mia_processes/python\', \'/data/Git_Projects/populse_mia/python/populse_mia\', \'/usr/lib64/python37.zip\', \'/usr/lib64/python3.7\', \'/usr/lib64/python3.7/lib-dynload\', \'/home/econdami/.local/lib/python3.7/site-packages\', \'/home/econdami/.local/lib/python3.7/site-packages/scikit_image-0.15.0-py3.7-linux-x86_64.egg\', \'/home/econdami/.local/lib/python3.7/site-packages/etelemetry-0.2.0-py3.7.egg\', \'/home/econdami/.local/lib/python3.7/site-packages/ci_info-0.1.1-py3.7.egg\', \'/home/econdami/.local/lib/python3.7/site-packages/six-1.14.0-py3.7.egg\', \'/home/econdami/.local/lib/python3.7/site-packages/rdflib-5.0.0-py3.7.egg\', \'/home/econdami/.local/lib/python3.7/site-packages/sip-5.0.1-py3.7-linux-x86_64.egg\', \'/home/econdami/.local/lib/python3.7/site-packages/nipype-1.6.0.dev0+ge1ea1980c-py3.7.egg\', \'/home/econdami/.local/lib/python3.7/site-packages/csv2report-0.1.0-py3.7.egg\', \'/usr/lib64/python3.7/site-packages\', \'/usr/lib/python3.7/site-packages\', \'/data/Git_Projects/populse_mia/processes\']; from capsul.api import Process; Process.run_from_commandline("mia_processes.preprocess.spm.spatial_preprocessing.Smooth")'
* exit value: 1
* term signal: None
---- env ----
None
---- configuration ----
{'capsul_engine': {'uses': {'capsul.engine.module.spm': 'any', 'capsul.engine.module.matlab': 'any'}}, 'capsul.engine.module.spm': {'config_id': 'spm12', 'config_environment': 'global', 'directory': '/usr/local/SPM/spm12', 'version': '12', 'standalone': False}, 'capsul.engine.module.matlab': {'config_id': 'matlab', 'config_environment': 'global', 'executable': '/usr/local/MATLAB/R2019b/bin/matlab'}}
---- stdout ----

---- stderr ----
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/data/Git_Projects/capsul/capsul/process/process.py", line 732, in run_from_commandline
    result = ce.study_config.run(process, configuration_dict=configuration)
  File "/data/Git_Projects/capsul/capsul/study_config/study_config.py", line 417, in run
    configuration_dict=configuration_dict)
  File "/data/Git_Projects/capsul/capsul/study_config/run.py", line 84, in run_process
    engine.activate_configuration(configuration_dict)
  File "/data/Git_Projects/capsul/capsul/engine/__init__.py", line 558, in activate_configuration
    activate_module(m)
  File "/data/Git_Projects/capsul/capsul/engine/__init__.py", line 580, in activate_module
    raise EnvironmentError(error)
OSError: MATLAB_EXECUTABLE is not defined

```
BUT if I remember well, we reached an agreement not to force the user to use environment variables?

_Originally posted by @servoz in https://github.com/populse/populse_mia/pull/165#issuecomment-652068049_

**Comment by denisri** [comment]
The matlab condig is actually passed to the job:
```'capsul.engine.module.matlab': {'config_id': 'matlab', 'config_environment': 'global', 'executable': '/usr/local/MATLAB/R2019b/bin/matlab'}```
so there is probably a bug in applying the config in its matlab module. I'll check that, but I don't have matlab, which is why I haven't tested it correclty.

**Comment by denisri** [comment]
does populse/capsul@03a7154 help ?

**Comment by servoz** [comment]
Yes populse/capsul@03a7154 help.
Currently  I'm forced to continue to use the 4PR165onMIA branch of capsul where I merged master, while removing the change in capsul/pipeline/pipeline_workflow.py made in [capsul#3fa407a68](https://github.com/denisri/capsul/commit/3fa407a6861e02d2ab67df3e5b98c1afba2508ae) which doesn't solve my problem.
Otherwise I can't use populse_mia in populse_db_2 branch (with populse_db in 2.0 branch) ... so without using the 4PR165onMIA branch of capsu l can't continue testing ...
So yes thanks to populse/capsul@03a7154 i I'm not stuck on the `OSError: MATLAB_EXECUTABLE is not defined` exception but now I am stuck here:
```
When the pipeline was launched, the following exception was raised: Error during workflow execution. Status=('finished_regularly', 1, None, None).
The workflow has not been removed from soma_workflow and must be deleted manually. 
Failed jobs: [48]
Aborted/killed jobs: []
============================================
---- failed job info ---
* job: 48: smooth1
* exit status: finished_regularly
* commandline:
'python3' '-c' 'import sys; sys.path = [\'/data/Git_Projects/populse_mia/python\', \'/data/Git_Projects/capsul\', \'/data/Git_Projects/soma-base/python\', \'/data/Git_Projects/soma-workflow/python\', \'/data/Git_Projects/populse_db/python\', \'/data/Git_Projects/mia_processes/python\', \'/data/Git_Projects/populse_mia/python/populse_mia\', \'/usr/lib64/python37.zip\', \'/usr/lib64/python3.7\', \'/usr/lib64/python3.7/lib-dynload\', \'/home/econdami/.local/lib/python3.7/site-packages\', \'/home/econdami/.local/lib/python3.7/site-packages/scikit_image-0.15.0-py3.7-linux-x86_64.egg\', \'/home/econdami/.local/lib/python3.7/site-packages/etelemetry-0.2.0-py3.7.egg\', \'/home/econdami/.local/lib/python3.7/site-packages/ci_info-0.1.1-py3.7.egg\', \'/home/econdami/.local/lib/python3.7/site-packages/six-1.14.0-py3.7.egg\', \'/home/econdami/.local/lib/python3.7/site-packages/rdflib-5.0.0-py3.7.egg\', \'/home/econdami/.local/lib/python3.7/site-packages/sip-5.0.1-py3.7-linux-x86_64.egg\', \'/home/econdami/.local/lib/python3.7/site-packages/nipype-1.6.0.dev0+ge1ea1980c-py3.7.egg\', \'/home/econdami/.local/lib/python3.7/site-packages/csv2report-0.1.0-py3.7.egg\', \'/usr/lib64/python3.7/site-packages\', \'/usr/lib/python3.7/site-packages\', \'/data/Git_Projects/populse_mia/processes\']; from capsul.api import Process; Process.run_from_commandline("mia_processes.preprocess.spm.spatial_preprocessing.Smooth")'
* exit value: 1
* term signal: None
---- env ----
None
---- configuration ----
{'capsul_engine': {'uses': {'capsul.engine.module.spm': 'any', 'capsul.engine.module.matlab': 'any'}}, 'capsul.engine.module.spm': {'config_id': 'spm12', 'config_environment': 'global', 'directory': '/usr/local/SPM/spm12', 'version': '12', 'standalone': False}, 'capsul.engine.module.matlab': {'config_id': 'matlab', 'config_environment': 'global', 'executable': '/usr/local/MATLAB/R2019b/bin/matlab'}}
---- stdout ----

---- stderr ----
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/data/Git_Projects/capsul/capsul/process/process.py", line 710, in run_from_commandline
    result = ce.study_config.run(process, configuration_dict=configuration)
  File "/data/Git_Projects/capsul/capsul/study_config/study_config.py", line 417, in run
    configuration_dict=configuration_dict)
  File "/data/Git_Projects/capsul/capsul/study_config/run.py", line 157, in run_process
    process_instance._before_run_process()
  File "/data/Git_Projects/populse_mia/python/populse_mia/user_interface/pipeline_manager/process_mia.py", line 80, in _before_run_process
    self.manage_brick_before_run()
  File "/data/Git_Projects/populse_mia/python/populse_mia/user_interface/pipeline_manager/process_mia.py", line 157, in manage_brick_before_run
    self.manage_brick_output_before_run(output_value)
  File "/data/Git_Projects/populse_mia/python/populse_mia/user_interface/pipeline_manager/process_mia.py", line 176, in manage_brick_output_before_run
    scan_bricks_history = self.get_scan_bricks(output_value)
  File "/data/Git_Projects/populse_mia/python/populse_mia/user_interface/pipeline_manager/process_mia.py", line 124, in get_scan_bricks
    for scan in self.project.session.get_documents_names(
AttributeError: 'Smooth' object has no attribute 'project'

```
I feel like I'm testing a Pandora's box...

**Comment by denisri** [comment]
Maybe it's better to test PR #167. I'm busy today and on vacation next week so we'll see that later, sorry.

**Comment by servoz** [comment]
no problem.
If I can find a couple of hours i will try to see this exception (It looks like a problem with adding to the database the history of the bricks used, which is updated at the time of the run).
But currently it will be nice to add 2 or 3 hours to each day (24h is definitively too short :-))) have a nice vacation. We will continue to play latter ...

**Comment by servoz** [comment]
to be sure ... PR #167 can replace the two PR #165 and #166 (if we merge #167 then we can trash #165 and #166) ?

**Comment by denisri** [comment]
Yes that's it.
I don't have much time to checck now but I suspect I did a mistake, merging too much things in master branch (things that were part of the capsulengine branch). Sorry.

**Comment by servoz** [comment]
no problem !
Only those who do nothing are never wrong... 
see you soon

**Comment by servoz** [comment]
You're absolutely right, it's better to test PR #167 directly because with populse_mia on the  populse_db2_capsulengine branch, populse_db on the 2.0 branch and capsul on the 4PR165onMIA branch (all the other capsul packages on master) I don't have the [previous](https://github.com/populse/populse_mia/issues/172#issuecomment-653242804) exception anymore:
`AttributeError: 'Smooth' object has no attribute 'project'`

but there's a new one:

 ```
When the pipeline was launched, the following exception was raised: Error during workflow execution. Status=('finished_regularly', 1, None, None).
The workflow has not been removed from soma_workflow and must be deleted manually. 
Failed jobs: [52]
Aborted/killed jobs: []
============================================
---- failed job info ---
* job: 52: smooth1
* exit status: finished_regularly
* commandline:
'python3' '-c' 'import sys; sys.path = [\'/data/Git_Projects/populse_mia/python\', \'/data/Git_Projects/capsul\', \'/data/Git_Projects/soma-base/python\', \'/data/Git_Projects/soma-workflow/python\', \'/data/Git_Projects/populse_db/python\', \'/data/Git_Projects/mia_processes/python\', \'/data/Git_Projects/populse_mia/python/populse_mia\', \'/usr/lib64/python37.zip\', \'/usr/lib64/python3.7\', \'/usr/lib64/python3.7/lib-dynload\', \'/home/econdami/.local/lib/python3.7/site-packages\', \'/home/econdami/.local/lib/python3.7/site-packages/scikit_image-0.15.0-py3.7-linux-x86_64.egg\', \'/home/econdami/.local/lib/python3.7/site-packages/etelemetry-0.2.0-py3.7.egg\', \'/home/econdami/.local/lib/python3.7/site-packages/ci_info-0.1.1-py3.7.egg\', \'/home/econdami/.local/lib/python3.7/site-packages/six-1.14.0-py3.7.egg\', \'/home/econdami/.local/lib/python3.7/site-packages/rdflib-5.0.0-py3.7.egg\', \'/home/econdami/.local/lib/python3.7/site-packages/sip-5.0.1-py3.7-linux-x86_64.egg\', \'/home/econdami/.local/lib/python3.7/site-packages/nipype-1.6.0.dev0+ge1ea1980c-py3.7.egg\', \'/home/econdami/.local/lib/python3.7/site-packages/csv2report-0.1.0-py3.7.egg\', \'/usr/lib64/python3.7/site-packages\', \'/usr/lib/python3.7/site-packages\', \'/data/Git_Projects/populse_mia/processes\']; from capsul.api import Process; Process.run_from_commandline("mia_processes.preprocess.spm.spatial_preprocessing.Smooth")'
* exit value: 1
* term signal: None
---- env ----
None
---- configuration ----
{'capsul_engine': {'uses': {'capsul.engine.module.spm': 'any', 'capsul.engine.module.matlab': 'any'}}, 'capsul.engine.module.spm': {'config_id': 'spm12', 'config_environment': 'global', 'directory': '/usr/local/SPM/spm12', 'version': '12', 'standalone': False}, 'capsul.engine.module.matlab': {'config_id': 'matlab', 'config_environment': 'global', 'executable': '/usr/local/MATLAB/R2019b/bin/matlab'}}
---- stdout ----

Changing from /data/Git_Projects/populse_mia/python/populse_mia directory to /data/IRM/projects_mia/test2.0_1/scripts directory ...


---- stderr ----
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/data/Git_Projects/capsul/capsul/process/process.py", line 710, in run_from_commandline
    result = ce.study_config.run(process, configuration_dict=configuration)
  File "/data/Git_Projects/capsul/capsul/study_config/study_config.py", line 417, in run
    configuration_dict=configuration_dict)
  File "/data/Git_Projects/capsul/capsul/study_config/run.py", line 158, in run_process
    returncode = process_instance._run_process()
  File "/data/Git_Projects/mia_processes/python/mia_processes/process_mia.py", line 68, in _run_process
    self.run_process_mia()
  File "/data/Git_Projects/mia_processes/python/mia_processes/preprocess/spm/spatial_preprocessing.py", line 1681, in run_process_mia
    self.process.run()
  File "/home/econdami/.local/lib/python3.7/site-packages/nipype-1.6.0.dev0+ge1ea1980c-py3.7.egg/nipype/interfaces/base/core.py", line 397, in run
    runtime = self._run_interface(runtime)
  File "/home/econdami/.local/lib/python3.7/site-packages/nipype-1.6.0.dev0+ge1ea1980c-py3.7.egg/nipype/interfaces/spm/base.py", line 385, in _run_interface
    deepcopy(self._parse_inputs())
  File "/home/econdami/.local/lib/python3.7/site-packages/nipype-1.6.0.dev0+ge1ea1980c-py3.7.egg/nipype/interfaces/spm/base.py", line 596, in _make_matlab_command
    {self.jobname: self.reformat_dict_for_savemat(contents[0])}
AttributeError: 'Smooth' object has no attribute 'reformat_dict_for_savemat'
```
I really don't have time to look deeper at it now. So I'm going to stay for now on the master branches for the whole populse project and I'll come back to this #167 PR later when I will have a bit more time.

**Comment by denisri** [comment]
I haven't understood why you need to be on a specific branch for capsul ? I'm working on master and it seems OK.
Not sure to have time but I'm trying to fix populse_mia/master...

**Comment by servoz** [comment]
on master mia crash at run because i have no populse package installed in site package (i run in dev mode, and i need to inject the sys.path as i proposed in the PR. To date we don't gave a workaround for that, just ideas ...)

**Comment by servoz** [comment]
I'm just starting to use again:
- capsul branch on master branch
- mia_process on master branch
- populse_db on 2.0 branch
- populse_mia on populse_db2_capsulengine branch (merged with master so that it is current master branch + populse_db2_capsulengine branch)
- soma-base on the master branch
- soma-workflow on the master branch

I use data coming from populse_mia/data_tests/Philips_files/Data_patient imported to mia thanks to mri_conv (in mia: File > Import)

Smooth brick from mia_processes test:
- using the T1 data (alej170316-IRMFonct.+perfusion-2016-03-17083444-0-T13DSENSE-T1TFE-000425.000.nii)

1- Initialisation take a while !!! roughly 2 mins (on master roughly 2 sec). A the end an entry is created in the data browser but in fact no data is created in the raw_data. I don't remember observing this in June ...

**Comment by servoz** [comment]
2- the launch of the smooth brick does of course crash mia (the opening of this issue).
I will continue the tests tomorrow using the 4PR165onMIA capsul branch which in June enabled the pipeline to be launched. But it is clear that an initialisation of a single smooth brick in 2 mins is an impediment.

**Comment by denisri** [comment]
I have pushed a modif (not a complete fix) for non-default parameters values handling (8c3c24d4adba1264798813c5df0dbb78bb0), which might be the cause for this issue.
I don't have matlab here but I had the same kind of problem with the use_mcr parameters.
A real fix would need a parameters locking system in Capsul.

**Comment by servoz** [comment]
Yeah ! Your fix is the good one ! Thanks @denisri.
So now I can launch the Smooth mia_processes with db 2.0 and mia populse_db2_capsulengine and capsul 4PR165onMIA (master not working yet)
