### ISSUE TITLE
Populse_mia crash when we want to save pipeline containing the 'mcflirt' module of FSL

### ISSUE THREAD

**Issue by montigno** [populse/populse_mia#202]
I created a pipeline which contains 2 'mcflirt' modules of FSL.
The first backup worked.

When I reopen it, edit and save, Populse_mia crash.

Here the error message 

<p></p>

	Exception hooking in progress ...

	Clean up before closing mia done ...

	Traceback (most recent call last):
  	File "/home/omontigon/Apps/python_populse_v2/populse_mia/python/populse_mia/user_interface/pipeline_manager/pipeline_editor.py", line 1670, in save_pipeline
    	[(key, (value.x(), value.y())) for key, value in
  	File "/home/omontigon/Apps/python_populse_v2/populse_mia/python/populse_mia/user_interface/pipeline_manager/pipeline_editor.py", line 1670, in <listcomp>
    	[(key, (value.x(), value.y())) for key, value in
	AttributeError: 'tuple' object has no attribute 'x'

	During handling of the above exception, another exception occurred:

	Traceback (most recent call last):
  	File "/home/omontigon/Apps/python_populse_v2/populse_mia/python/populse_mia/user_interface/main_window.py", line 806, in save
    	self.pipeline_manager.savePipeline()
  	File "/home/omontigon/Apps/python_populse_v2/populse_mia/python/populse_mia/user_interface/pipeline_manager/pipeline_manager_tab.py", line 1860, in savePipeline
    	self.pipelineEditorTabs.save_pipeline(new_file_name=filename)
  	File "/home/omontigon/Apps/python_populse_v2/populse_mia/python/populse_mia/user_interface/pipeline_manager/pipeline_editor.py", line 1674, in save_pipeline
    	[(key, (value[0], value[1])) for key, value in
  	File "/home/omontigon/Apps/python_populse_v2/populse_mia/python/populse_mia/user_interface/pipeline_manager/pipeline_editor.py", line 1674, in <listcomp>
    	[(key, (value[0], value[1])) for key, value in
	TypeError: 'QPointF' object is not subscriptable
<p></p>

**Comment by servoz** [comment]
I have just tested (but with only one brick) and I don't observe any crash.
Please, can you provide a minimum procedure to reproduce the crash?

**Comment by montigno** [comment]
I am teleworking this afternoon and I redid the procedure on my personal computer and strangely I have no problem.
I will try again on my desktop next week.

**Comment by servoz** [comment]
Great!!! teleworking is good for development! May be a version issue ?
I close this ticket, of course, feel free to reopen if necessary!
