### ISSUE TITLE
[general need] Mia V2 does not accept user error

### ISSUE THREAD

**Issue by servoz** [populse/populse_mia#228]
Minimum step to reproduce :

- Drag and drop the mia_processes.bricks.preprocess.spm.`Smooth` brick from the package library to an editor in the Pipeline Manager tab.
- Initialise the pipeline (this is a user error as initialise a pipeline without mandatory input parameters does not make sense).
- Click the OK button in the pop-up window indicating that the initialisation could not be completed.
- So complete the pipeline correctly to perform an effective initialisation:
  - Right-click on the `Smooth` node and select `export all unconnected plugs`.
  - In the controller, click on the `Filter` button for the `in_files parameter`, select a data from the database.
- Initialise the pipeline:
  - The initialisation falls with the following exception in the stdout:

```
Exception occurred in traits notification handler for object: <populse_mia.user_interface.pipeline_manager.process_mia.MIAProcessCompletionEngine object at 0x7fed06cb4770>, trait: completion_progress, old value: 1.0, new value: 0.0
Traceback (most recent call last):
  File "/home/econdami/.local/lib/python3.8/site-packages/traits/trait_notifiers.py", line 524, in _dispatch_change_event
    self.dispatch(handler, *args)
  File "/home/econdami/.local/lib/python3.8/site-packages/traits/trait_notifiers.py", line 619, in dispatch
    handler(*args)
  File "/home/econdami/Git_Projects/capsul/capsul/qt_gui/widgets/attributed_process_widget.py", line 430, in _completion_progress_changed
    if not hasattr(self, 'progressdialog'):
RuntimeError: wrapped C/C++ object of type AttributedProcessWidget has been deleted

```

**Comment by servoz** [comment]
The tests carried out today seem to indicate that this issue is no longer observed.
There is a good chance that this is the happy outcome of the previous e13d399 commit!
