### ISSUE TITLE
[mia preferences] MATLAB:mpath:PathAlterationNotSupported / Modifying the search path is not supported by MATLAB Compiler using MAtlab 2019b

### ISSUE THREAD

**Issue by servoz** [populse/populse_mia#238]
It seems modifying the matlab path using addpath() is not likely to be supported at any point after MATLAB MCR_R2018b.

I just tested Smooth brick from mia_processes with MCR_R2019b. The run fail with:

```
- Pipeline running ...

soma-workflow starting in light mode
Workflow controller initialised
set exec status on: 9afafe8d-fb6b-4354-ac02-345a73cf7428 2021-11-10 14:29:58
obsolete bricks: set()
really orphan: set()
  =================================================
environ({'SHELL': '/bin/bash', 'SESSION_MANAGER': 'local/Precision-T3610:@/tmp/.ICE-unix/1875,unix/Precision-T3610:/tmp/.ICE-unix/1875', 'QT_ACCESSIBILITY': '1', 'COLORTERM': 'truecolor', 'XDG_CONFIG_DIRS': '/etc/xdg/xdg-ubuntu:/etc/xdg', 'SSH_AGENT_LAUNCHER': 'gnome-keyring', 'XDG_MENU_PREFIX': 'gnome-', 'GNOME_DESKTOP_SESSION_ID': 'this-is-deprecated', 'LC_ADDRESS': 'fr_FR.UTF-8', 'GNOME_SHELL_SESSION_MODE': 'ubuntu', 'LC_NAME': 'fr_FR.UTF-8', 'SSH_AUTH_SOCK': '/run/user/1002/keyring/ssh', 'XMODIFIERS': '@im=ibus', 'DESKTOP_SESSION': 'ubuntu', 'LC_MONETARY': 'fr_FR.UTF-8', 'EDITOR': '/usr/bin/nano', 'GTK_MODULES': 'gail:atk-bridge', 'PWD': '/home/lucas/projects/populse/populse_mia/python/populse_mia', 'LOGNAME': 'lucas', 'XDG_SESSION_DESKTOP': 'ubuntu', 'XDG_SESSION_TYPE': 'x11', 'GPG_AGENT_INFO': '/run/user/1002/gnupg/S.gpg-agent:0:1', 'XAUTHORITY': '/run/user/1002/gdm/Xauthority', 'GJS_DEBUG_TOPICS': 'JS ERROR;JS LOG', 'WINDOWPATH': '2', 'VIRTUALENVWRAPPER_SCRIPT': '/usr/local/bin/virtualenvwrapper.sh', 'HOME': '/home/lucas', 'USERNAME': 'lucas', 'IM_CONFIG_PHASE': '1', 'LC_PAPER': 'fr_FR.UTF-8', 'LANG': 'en_US.UTF-8', 'LS_COLORS': 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.webp=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:', 'XDG_CURRENT_DESKTOP': 'ubuntu:GNOME', 'VTE_VERSION': '6203', 'QT_API': 'pyqt5', 'VIRTUALENVWRAPPER_WORKON_CD': '1', 'GNOME_TERMINAL_SCREEN': '/org/gnome/Terminal/screen/558c35ac_36cd_4201_81bb_a91fb6808996', 'VIRTUALENVWRAPPER_PYTHON': '/usr/bin/python3', 'GJS_DEBUG_OUTPUT': 'stderr', 'WORKON_HOME': '/home/lucas/.virtualenvs', 'LESSCLOSE': '/usr/bin/lesspipe %s %s', 'XDG_SESSION_CLASS': 'user', 'TERM': 'xterm-256color', 'LC_IDENTIFICATION': 'fr_FR.UTF-8', 'LESSOPEN': '| /usr/bin/lesspipe %s', 'USER': 'lucas', 'GNOME_TERMINAL_SERVICE': ':1.94', 'VISUAL': '/usr/bin/nano', 'VIRTUALENVWRAPPER_PROJECT_FILENAME': '.project', 'DISPLAY': ':1', 'ETS_TOOLKIT': 'qt4', 'SHLVL': '1', 'LC_TELEPHONE': 'fr_FR.UTF-8', 'QT_IM_MODULE': 'ibus', 'LC_MEASUREMENT': 'fr_FR.UTF-8', 'XDG_RUNTIME_DIR': '/run/user/1002', 'LC_TIME': 'fr_FR.UTF-8', 'XDG_DATA_DIRS': '/usr/share/ubuntu:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop', 'PATH': '/home/lucas/Qt/5.12.11/gcc_64/lib:/home/lucas/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin', 'VIRTUALENVWRAPPER_HOOK_DIR': '/home/lucas/.virtualenvs', 'GDMSESSION': 'ubuntu', 'DBUS_SESSION_BUS_ADDRESS': 'unix:path=/run/user/1002/bus', 'PROJECT_HOME': '/home/lucas/Devel', 'LC_NUMERIC': 'fr_FR.UTF-8', 'OLDPWD': '/home/lucas/projects/populse/populse_mia/python', '_': '/usr/bin/python3', 'NO_ET': '1'})
  =================================================
environ({'SHELL': '/bin/bash', 'SESSION_MANAGER': 'local/Precision-T3610:@/tmp/.ICE-unix/1875,unix/Precision-T3610:/tmp/.ICE-unix/1875', 'QT_ACCESSIBILITY': '1', 'COLORTERM': 'truecolor', 'XDG_CONFIG_DIRS': '/etc/xdg/xdg-ubuntu:/etc/xdg', 'SSH_AGENT_LAUNCHER': 'gnome-keyring', 'XDG_MENU_PREFIX': 'gnome-', 'GNOME_DESKTOP_SESSION_ID': 'this-is-deprecated', 'LC_ADDRESS': 'fr_FR.UTF-8', 'GNOME_SHELL_SESSION_MODE': 'ubuntu', 'LC_NAME': 'fr_FR.UTF-8', 'SSH_AUTH_SOCK': '/run/user/1002/keyring/ssh', 'XMODIFIERS': '@im=ibus', 'DESKTOP_SESSION': 'ubuntu', 'LC_MONETARY': 'fr_FR.UTF-8', 'EDITOR': '/usr/bin/nano', 'GTK_MODULES': 'gail:atk-bridge', 'PWD': '/home/lucas/projects/populse/populse_mia/python/populse_mia', 'LOGNAME': 'lucas', 'XDG_SESSION_DESKTOP': 'ubuntu', 'XDG_SESSION_TYPE': 'x11', 'GPG_AGENT_INFO': '/run/user/1002/gnupg/S.gpg-agent:0:1', 'XAUTHORITY': '/run/user/1002/gdm/Xauthority', 'GJS_DEBUG_TOPICS': 'JS ERROR;JS LOG', 'WINDOWPATH': '2', 'VIRTUALENVWRAPPER_SCRIPT': '/usr/local/bin/virtualenvwrapper.sh', 'HOME': '/home/lucas', 'USERNAME': 'lucas', 'IM_CONFIG_PHASE': '1', 'LC_PAPER': 'fr_FR.UTF-8', 'LANG': 'en_US.UTF-8', 'LS_COLORS': 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.webp=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:', 'XDG_CURRENT_DESKTOP': 'ubuntu:GNOME', 'VTE_VERSION': '6203', 'QT_API': 'pyqt5', 'VIRTUALENVWRAPPER_WORKON_CD': '1', 'GNOME_TERMINAL_SCREEN': '/org/gnome/Terminal/screen/558c35ac_36cd_4201_81bb_a91fb6808996', 'VIRTUALENVWRAPPER_PYTHON': '/usr/bin/python3', 'GJS_DEBUG_OUTPUT': 'stderr', 'WORKON_HOME': '/home/lucas/.virtualenvs', 'LESSCLOSE': '/usr/bin/lesspipe %s %s', 'XDG_SESSION_CLASS': 'user', 'TERM': 'xterm-256color', 'LC_IDENTIFICATION': 'fr_FR.UTF-8', 'LESSOPEN': '| /usr/bin/lesspipe %s', 'USER': 'lucas', 'GNOME_TERMINAL_SERVICE': ':1.94', 'VISUAL': '/usr/bin/nano', 'VIRTUALENVWRAPPER_PROJECT_FILENAME': '.project', 'DISPLAY': ':1', 'ETS_TOOLKIT': 'qt4', 'SHLVL': '1', 'LC_TELEPHONE': 'fr_FR.UTF-8', 'QT_IM_MODULE': 'ibus', 'LC_MEASUREMENT': 'fr_FR.UTF-8', 'XDG_RUNTIME_DIR': '/run/user/1002', 'LC_TIME': 'fr_FR.UTF-8', 'XDG_DATA_DIRS': '/usr/share/ubuntu:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop', 'PATH': '/home/lucas/Qt/5.12.11/gcc_64/lib:/home/lucas/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin', 'VIRTUALENVWRAPPER_HOOK_DIR': '/home/lucas/.virtualenvs', 'GDMSESSION': 'ubuntu', 'DBUS_SESSION_BUS_ADDRESS': 'unix:path=/run/user/1002/bus', 'PROJECT_HOME': '/home/lucas/Devel', 'LC_NUMERIC': 'fr_FR.UTF-8', 'OLDPWD': '/home/lucas/projects/populse/populse_mia/python', '_': '/usr/bin/python3', 'NO_ET': '1'})

 When the pipeline was launched, the following exception was raised: Error during workflow execution. Status=workflow_failed.
The workflow has not been removed from soma_workflow and must be deleted manually. 
Failed jobs: [24]
Aborted/killed jobs: []
** Workflow status OK
** Jobs failure, the following jobs ended with failed status:
+ job: smooth_1 , status: done , exit: finished_regularly , value: 1
  commandline:
'/usr/bin/python3' '-c' 'import sys; sys.path = [\'/home/lucas/projects/populse/populse_mia/python\', \'/home/lucas/projects/populse/capsul/\', \'/home/lucas/projects/populse/soma-base/python\', \'/home/lucas/projects/populse/soma-workflow/python\', \'/home/lucas/projects/populse/populse_db/python\', \'/home/lucas/projects/populse/mia_processes/python\', \'/home/lucas/projects/populse/populse_mia/processes\'] + sys.path; from capsul.api import Process; Process.run_from_commandline("mia_processes.bricks.preprocess.spm.spatial_preprocessing.Smooth")'

** Failed jobs outputs:

+ job 24: smooth_1 , status: done , exit: finished_regularly , value: 1
  commandline:
  ------------:
'/usr/bin/python3' '-c' 'import sys; sys.path = [\'/home/lucas/projects/populse/populse_mia/python\', \'/home/lucas/projects/populse/capsul/\', \'/home/lucas/projects/populse/soma-base/python\', \'/home/lucas/projects/populse/soma-workflow/python\', \'/home/lucas/projects/populse/populse_db/python\', \'/home/lucas/projects/populse/mia_processes/python\', \'/home/lucas/projects/populse/populse_mia/processes\'] + sys.path; from capsul.api import Process; Process.run_from_commandline("mia_processes.bricks.preprocess.spm.spatial_preprocessing.Smooth")'

  input parameters:
  -----------------
{'in_files': ['/home/lucas/projects/mia_projects/test/data/raw_data/alej170316-IRMFonct_+perfusion-2016-03-17083444-00-T13DSENSE-T1TFE-000425_000.nii'], 'fwhm': [6.0, 6.0, 6.0], 'data_type': 0, 'implicit_masking': False, 'out_prefix': 's', 'smoothed_files': '/home/lucas/projects/mia_projects/test/data/derived_data/salej170316-IRMFonct_+perfusion-2016-03-17083444-00-T13DSENSE-T1TFE-000425_000.nii', 'output_directory': '/home/lucas/projects/mia_projects/test/data/derived_data', 'use_mcr': True, 'paths': ['/home/lucas/SPM/standalone_spm12_r7771_R2019b/spm12'], 'matlab_cmd': '/home/lucas/SPM/standalone_spm12_r7771_R2019b/spm12/run_spm12.sh /home/lucas/MATLAB/MCR_R2019b/v97 script', 'mfile': True, 'spm_script_file': '/home/lucas/projects/mia_projects/test/scripts/pyscript_smooth_9afafe8d-fb6b-4354-ac02-345a73cf7428.m'}

  output parameters:
  ------------------
None

  environment:
  ------------
{'SOMAWF_INPUT_PARAMS': '/home/lucas/.soma-workflow/transfered_files/lucas_1/648', 'SOMAWF_OUTPUT_PARAMS': '/home/lucas/.soma-workflow/transfered_files/lucas_1/649'}

  standard output:
  ----------------



  standard error:
  ---------------

EXCEPTION: 'NoneType' object is not iterable
while syncing nipype parameter output_directory on Smooth
Traceback (most recent call last):
  File "/home/lucas/projects/populse/capsul/capsul/process/nipype_process.py", line 178, in sync_process_output_traits
    nipype_outputs = (process_instance.
  File "/home/lucas/.local/lib/python3.9/site-packages/nipype-1.7.0-py3.9.egg/nipype/interfaces/spm/preprocess.py", line 2175, in _list_outputs
    for imgf in ensure_list(self.inputs.in_files):
TypeError: 'NoneType' object is not iterable
EXCEPTION: 'NoneType' object is not iterable
while syncing nipype parameter use_mcr on Smooth
Traceback (most recent call last):
  File "/home/lucas/projects/populse/capsul/capsul/process/nipype_process.py", line 178, in sync_process_output_traits
    nipype_outputs = (process_instance.
  File "/home/lucas/.local/lib/python3.9/site-packages/nipype-1.7.0-py3.9.egg/nipype/interfaces/spm/preprocess.py", line 2175, in _list_outputs
    for imgf in ensure_list(self.inputs.in_files):
TypeError: 'NoneType' object is not iterable
EXCEPTION: 'NoneType' object is not iterable
while syncing nipype parameter paths on Smooth
Traceback (most recent call last):
  File "/home/lucas/projects/populse/capsul/capsul/process/nipype_process.py", line 178, in sync_process_output_traits
    nipype_outputs = (process_instance.
  File "/home/lucas/.local/lib/python3.9/site-packages/nipype-1.7.0-py3.9.egg/nipype/interfaces/spm/preprocess.py", line 2175, in _list_outputs
    for imgf in ensure_list(self.inputs.in_files):
TypeError: 'NoneType' object is not iterable
EXCEPTION: 'NoneType' object is not iterable
while syncing nipype parameter matlab_cmd on Smooth
Traceback (most recent call last):
  File "/home/lucas/projects/populse/capsul/capsul/process/nipype_process.py", line 178, in sync_process_output_traits
    nipype_outputs = (process_instance.
  File "/home/lucas/.local/lib/python3.9/site-packages/nipype-1.7.0-py3.9.egg/nipype/interfaces/spm/preprocess.py", line 2175, in _list_outputs
    for imgf in ensure_list(self.inputs.in_files):
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/lucas/projects/populse/capsul/capsul/process/process.py", line 731, in run_from_commandline
    result = ce.study_config.run(process, configuration_dict=configuration)
  File "/home/lucas/projects/populse/capsul/capsul/study_config/study_config.py", line 423, in run
    result, log_file = run_process(
  File "/home/lucas/projects/populse/capsul/capsul/study_config/run.py", line 165, in run_process
    returncode = process_instance._run_process()
  File "/home/lucas/projects/populse/populse_mia/python/populse_mia/user_interface/pipeline_manager/process_mia.py", line 517, in _run_process
    self.run_process_mia()
  File "/home/lucas/projects/populse/mia_processes/python/mia_processes/bricks/preprocess/spm/spatial_preprocessing.py", line 2422, in run_process_mia
    return self.process.run(configuration_dict={})
  File "/home/lucas/projects/populse/capsul/capsul/process/process.py", line 310, in run
    return self.__call__(**kwargs)
  File "/home/lucas/projects/populse/capsul/capsul/process/process.py", line 302, in __call__
    returncode = self.get_study_config().run(self, **kwargs)
  File "/home/lucas/projects/populse/capsul/capsul/study_config/study_config.py", line 423, in run
    result, log_file = run_process(
  File "/home/lucas/projects/populse/capsul/capsul/study_config/run.py", line 165, in run_process
    returncode = process_instance._run_process()
  File "/home/lucas/projects/populse/capsul/capsul/process/process.py", line 1877, in _run_process
    results = self._nipype_interface.run()
  File "/home/lucas/.local/lib/python3.9/site-packages/nipype-1.7.0-py3.9.egg/nipype/interfaces/base/core.py", line 398, in run
    runtime = self._run_interface(runtime)
  File "/home/lucas/.local/lib/python3.9/site-packages/nipype-1.7.0-py3.9.egg/nipype/interfaces/spm/base.py", line 387, in _run_interface
    results = self.mlab.run()
  File "/home/lucas/.local/lib/python3.9/site-packages/nipype-1.7.0-py3.9.egg/nipype/interfaces/base/core.py", line 398, in run
    runtime = self._run_interface(runtime)
  File "/home/lucas/.local/lib/python3.9/site-packages/nipype-1.7.0-py3.9.egg/nipype/interfaces/matlab.py", line 164, in _run_interface
    self.raise_exception(runtime)
  File "/home/lucas/.local/lib/python3.9/site-packages/nipype-1.7.0-py3.9.egg/nipype/interfaces/base/core.py", line 673, in raise_exception
    raise RuntimeError(
RuntimeError: Command:
/home/lucas/SPM/standalone_spm12_r7771_R2019b/spm12/run_spm12.sh /home/lucas/MATLAB/MCR_R2019b/v97 script /home/lucas/projects/mia_projects/test/data/derived_data/Smootha62a8g2z/pyscript_smooth.m
Standard output:
------------------------------------------
Setting up environment variables
---
LD_LIBRARY_PATH is .:/home/lucas/MATLAB/MCR_R2019b/v97/runtime/glnxa64:/home/lucas/MATLAB/MCR_R2019b/v97/bin/glnxa64:/home/lucas/MATLAB/MCR_R2019b/v97/sys/os/glnxa64:/home/lucas/MATLAB/MCR_R2019b/v97/sys/opengl/lib/glnxa64
SPM12, version 7771 (standalone)
MATLAB, version 9.7.0.1737446 (R2019b) Update 9
 ___  ____  __  __                                            
/ __)(  _ \(  \/  )                                           
\__ \ )___/ )    (   Statistical Parametric Mapping           
(___/(__)  (_/\/\_)  SPM12 - https://www.fil.ion.ucl.ac.uk/spm/

Executing /home/lucas/projects/mia_projects/test/data/derived_data/Smootha62a8g2z/pyscript_smooth.m at 10-Nov-2021 14:29:53:
-----------------------------------------------------------------------------------------------------
MATLAB Version: 9.7.0.1737446 (R2019b) Update 9
MATLAB License Number: unknown
Operating System: Linux 5.11.0-40-generic #44-Ubuntu SMP Wed Oct 20 16:16:42 UTC 2021 x86_64
Java Version: Java 1.8.0_202-b08 with Oracle Corporation Java HotSpot(TM) 64-Bit Server VM mixed mode
-----------------------------------------------------------------------------------------------------
MATLAB                                                Version 9.7         (R2019b)
MATLAB Compiler                                       Version 7.1         (R2019b)
Standard error:
MATLAB code threw an exception:
Modifying the search path is not supported by MATLAB Compiler. Remove functions that modify the search path from your MATLAB code. To make files visible to your deployed application, add the parent folder to your MATLAB session.
File:/home/lucas/MATLAB/MCR_R2019b/v97/mcr/toolbox/matlab/general/path.m
Name:/home/lucas/MATLAB/MCR_R2019b/v97/mcr/toolbox/matlab/general/addpath.m
Line:47
File:home/lucas/SPM/standalone_spm12_r7771_R2019b/spm12/spm12_mcr/spm12/spm12/spm.m
Name:/home/lucas/SPM/standalone_spm12_r7771_R2019b/spm12/spm12_mcr/spm12/spm12/spm_standalone.m
Line:112
File:ath
Name:addpath
Line:115
File:pm
Name:spm_standalone
Line:109
File:V
Name:ѻ
Line:115
Return code: 0


---- full host env ----
```
This is not observed with MATLAB MCR_R2018b.
So the easy fix is to stick with R2018b.

However commenting the line with the addpath() command in the matlab script generated on the fly during the calculation run fixed the issue with MCR_R2019b:

```
fprintf(1,'Executing %s at %s:\n',mfilename(),datestr(now));
ver,
try,
cd('/home/lucas/projects/mia_projects/test/data/derived_data');
%%%% addpath('/home/lucas/SPM/standalone_spm12_r7771_R2019b/spm12'); <====== addpath() comment

        %% Generated by nipype.interfaces.spm
        if isempty(which('spm')),
             throw(MException('SPMCheck:NotFound', 'SPM not in matlab path'));
        end
        [name, version] = spm('ver');
        fprintf('SPM version: %s Release: %s\n',name, version);
        fprintf('SPM path: %s\n', which('spm'));
        spm('Defaults','fMRI');

        if strcmp(name, 'SPM8') || strcmp(name(1:5), 'SPM12'),
           spm_jobman('initcfg');
           spm_get_defaults('cmdline', 1);
        end

        jobs{1}.spm.spatial.smooth.data = {...
'/home/lucas/projects/mia_projects/test/data/derived_data/Smootha97ks37a/alej170316-IRMFonct_+perfusion-2016-03-17083444-00-T13DSENSE-T1TFE-000425_000.nii,1';...
};
jobs{1}.spm.spatial.smooth.fwhm(1) = 6.0;
jobs{1}.spm.spatial.smooth.fwhm(2) = 6.0;
jobs{1}.spm.spatial.smooth.fwhm(3) = 6.0;
jobs{1}.spm.spatial.smooth.dtype = 0;
jobs{1}.spm.spatial.smooth.im = 0;
jobs{1}.spm.spatial.smooth.prefix = 's';

        spm_jobman('run', jobs);

        
        if strcmp(name, 'SPM8') || strcmp(name(1:5), 'SPM12'),
            close('all', 'force');
        end;
            
,catch ME,
fprintf(2,'MATLAB code threw an exception:\n');
fprintf(2,'%s\n',ME.message);
if length(ME.stack) ~= 0, fprintf(2,'File:%s\nName:%s\nLine:%d\n',ME.stack.file,ME.stack.name,ME.stack.line);, end;
end;

```
So I don't know if this ticket is just an information for users so that they don't use a version above MATLAB MCR_R2018b, or if it's a ticket that asks for a real change in the codes.
We could consider to modify the creation of the script by not using the addpath(). In mia, capsul, nypipe?
This would require some work to determine exactly where it is done.

But above all, is it necessary to spend energy if it is enough to stay with MATLAB MCR_R2018b?

**Comment by LStruber** [comment]
In my opinion we can stay with MATLAB MCR_R2018b, as long as it is maintained !

**Comment by servoz** [comment]
+1

**Comment by servoz** [comment]
if everyone agrees that it is urgent to do nothing, I propose to leave this ticket open for a while, that will leave us the joy of closing it on a sad day!
