### ISSUE TITLE
UT are currently failing

### ISSUE THREAD

**Issue by servoz** [populse/populse_mia#244]
======================================================================
ERROR: test_undo_redo (test.TestMIAPipelineManager)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/casa/home/Git_projects/populse_mia/python/populse_mia/test.py", line 2441, in test_undo_redo
    pipeline_manager.undo()
  File "/casa/home/Git_projects/populse_mia/python/populse_mia/user_interface/pipeline_manager/pipeline_manager_tab.py", line 2159, in undo
    parameter].output:
KeyError: 'prefix_smooth'

**Comment by servoz** [comment]
eb8f1de commit closes this ticket.
