### ISSUE TITLE
Mia does not support now a pipeline launching without input parameters error.

### ISSUE THREAD

**Issue by servoz** [populse/populse_mia#255]
The minimum steps to reproduce :

- Open Mia
- Open a project
- In the pipeline manager, drag and drop the SPM Smooth brick from mia_processes into the editor
- Click on the "Run pipeline" button (this is an error as we have not yet defined the input parameters, but errors should be handled in Mia).
- We observe in the status bar: Pipeline "NoName" was not initialised successfully and in the stdout:
```
 Pipeline initialising ...
Completion / workflow...
. main (mia_processes.bricks.preprocess.spm.spatial_preprocessing.Smooth) MIA node ...
During the <mia_processes.bricks.preprocess.spm.spatial_preprocessing.Smooth object at 0x7f8b95c12bf8> process initialisation, some possible problems were detected:
- inheritance_dict attribute was not found ...
- outputs attribute was not found ...
Workflow done.
Error during initialisation of the "NoName" pipeline ...!
Traceback:
  File "/casa/home/Git_projects/populse_mia/python/populse_mia/user_interface/pipeline_manager/pipeline_manager_tab.py", line 1301, in initialize
    self.test_init = self.init_pipeline()
  File "/casa/home/Git_projects/populse_mia/python/populse_mia/user_interface/pipeline_manager/pipeline_manager_tab.py", line 1385, in init_pipeline
    missing_inputs = self.get_missing_mandatory_parameters()
  File "/casa/home/Git_projects/populse_mia/python/populse_mia/user_interface/pipeline_manager/pipeline_manager_tab.py", line 1278, in get_missing_mandatory_parameters
    if node is self.get_current_pipeline().pipeline_node:
AttributeError: 'PipelineManagerTab' object has no attribute 'get_current_pipeline'

```
- If we now want to get things right it seems impossible:
  - Right click in the brick and choose "Export all unconnected records" (all nodes turn blue)
  - Select a in_files parameter using the Filter button
  - Click on the "Run pipeline" button
  - A pop-up window open with the message "The pipeline could not be initailsed properly"
  - We see in stdout:

```
 ERROR:traits:Exception occurred in traits notification handler for object: <mia_processes.bricks.preprocess.spm.spatial_preprocessing.Smooth object at 0x7f8b95c12bf8>, trait: in_files, old value: <undefined>, new value: ['/data/IRM/projects_mia/rel2_test/data/raw_data/rocmi_120618test1-IRMFonct_+perfusion-2018-06-12060428-05-T13DSENSE-T1TFE-000424_000.nii']
Traceback (most recent call last):
  File "/casa/home/.local/lib/python3.6/site-packages/traits/trait_notifiers.py", line 524, in _dispatch_change_event
    self.dispatch(handler, *args)
  File "/casa/home/.local/lib/python3.6/site-packages/traits/trait_notifiers.py", line 486, in dispatch
    handler(*args)
  File "/casa/host/build/python/soma/utils/functiontools.py", line 89, in __call__
    return self.func(*(self.args + args), **merged_kwargs)
  File "/casa/host/src/capsul/master/capsul/pipeline/pipeline_nodes.py", line 231, in _value_callback
    self.is_parameter_protected(source_plug_name))
  File "/casa/host/src/capsul/master/capsul/pipeline/pipeline_nodes.py", line 733, in set_plug_value
    elif is_trait_pathname(self.process.trait(plug_name)) and value is None:
  File "/casa/host/src/capsul/master/capsul/pipeline/pipeline_nodes.py", line 206, in process
    return get_ref(self._process)
  File "/casa/host/build/python/soma/utils/weak_proxy.py", line 51, in get_ref
    if isinstance(obj, weakref.ReferenceType):
ReferenceError: weakly-referenced object no longer exists
ERROR:traits:Exception occurred in traits notification handler for object: <capsul.pipeline.pipeline.Pipeline object at 0x7f8bb210e360>, trait: in_files, old value: <undefined>, new value: ['/data/IRM/projects_mia/rel2_test/data/raw_data/rocmi_120618test1-IRMFonct_+perfusion-2018-06-12060428-05-T13DSENSE-T1TFE-000424_000.nii']
Traceback (most recent call last):
  File "/casa/home/.local/lib/python3.6/site-packages/traits/trait_notifiers.py", line 524, in _dispatch_change_event
    self.dispatch(handler, *args)
  File "/casa/home/.local/lib/python3.6/site-packages/traits/trait_notifiers.py", line 486, in dispatch
    handler(*args)
  File "/casa/host/build/python/soma/utils/functiontools.py", line 89, in __call__
    return self.func(*(self.args + args), **merged_kwargs)
  File "/casa/host/src/capsul/master/capsul/pipeline/pipeline_nodes.py", line 231, in _value_callback
    self.is_parameter_protected(source_plug_name))
  File "/casa/host/src/capsul/master/capsul/pipeline/pipeline_nodes.py", line 735, in set_plug_value
    self.process.set_parameter(plug_name, value, protected)
  File "/casa/host/src/capsul/master/capsul/process/process.py", line 1043, in set_parameter
    setattr(self, name, value)
  File "/casa/home/.local/lib/python3.6/site-packages/traits/trait_notifiers.py", line 478, in __call__
    self.notify_listener(self, object, trait_name, old, new)
  File "/casa/home/.local/lib/python3.6/site-packages/traits/trait_notifiers.py", line 561, in _notify_function_listener
    object, trait_name, old, new, self.handler
  File "/casa/home/.local/lib/python3.6/site-packages/traits/trait_notifiers.py", line 532, in _dispatch_change_event
    handle_exception(object, trait_name, old, new)
  File "/casa/home/.local/lib/python3.6/site-packages/traits/trait_notifiers.py", line 149, in _handle_exception
    raise excp
  File "/casa/home/.local/lib/python3.6/site-packages/traits/trait_notifiers.py", line 524, in _dispatch_change_event
    self.dispatch(handler, *args)
  File "/casa/home/.local/lib/python3.6/site-packages/traits/trait_notifiers.py", line 486, in dispatch
    handler(*args)
  File "/casa/host/build/python/soma/utils/functiontools.py", line 89, in __call__
    return self.func(*(self.args + args), **merged_kwargs)
  File "/casa/host/src/capsul/master/capsul/pipeline/pipeline_nodes.py", line 231, in _value_callback
    self.is_parameter_protected(source_plug_name))
  File "/casa/host/src/capsul/master/capsul/pipeline/pipeline_nodes.py", line 733, in set_plug_value
    elif is_trait_pathname(self.process.trait(plug_name)) and value is None:
  File "/casa/host/src/capsul/master/capsul/pipeline/pipeline_nodes.py", line 206, in process
    return get_ref(self._process)
  File "/casa/host/build/python/soma/utils/weak_proxy.py", line 51, in get_ref
    if isinstance(obj, weakref.ReferenceType):
ReferenceError: weakly-referenced object no longer exists
weakly-referenced object no longer exists
ERROR:traits:Exception occurred in traits notification handler for object: <mia_processes.bricks.preprocess.spm.spatial_preprocessing.Smooth object at 0x7f8b95c12bf8>, trait: in_files, old value: ['/data/IRM/projects_mia/rel2_test/data/raw_data/rocmi_120618test1-IRMFonct_+perfusion-2018-06-12060428-05-T13DSENSE-T1TFE-000424_000.nii'], new value: ['/data/IRM/projects_mia/rel2_test/data/raw_data/alej170316_test24042018-IRMFonct_+perfusion-2016-03-17083444-00-T13DSENSE-T1TFE-000425_000.nii']
Traceback (most recent call last):
  File "/casa/home/.local/lib/python3.6/site-packages/traits/trait_notifiers.py", line 524, in _dispatch_change_event
    self.dispatch(handler, *args)
  File "/casa/home/.local/lib/python3.6/site-packages/traits/trait_notifiers.py", line 486, in dispatch
    handler(*args)
  File "/casa/host/build/python/soma/utils/functiontools.py", line 89, in __call__
    return self.func(*(self.args + args), **merged_kwargs)
  File "/casa/host/src/capsul/master/capsul/pipeline/pipeline_nodes.py", line 231, in _value_callback
    self.is_parameter_protected(source_plug_name))
  File "/casa/host/src/capsul/master/capsul/pipeline
 /pipeline_nodes.py", line 733, in set_plug_value
    elif is_trait_pathname(self.process.trait(plug_name)) and value is None:
  File "/casa/host/src/capsul/master/capsul/pipeline/pipeline_nodes.py", line 206, in process
    return get_ref(self._process)
  File "/casa/host/build/python/soma/utils/weak_proxy.py", line 51, in get_ref
    if isinstance(obj, weakref.ReferenceType):
ReferenceError: weakly-referenced object no longer exists
ERROR:traits:Exception occurred in traits notification handler for object: <capsul.pipeline.pipeline.Pipeline object at 0x7f8bb210e360>, trait: in_files, old value: ['/data/IRM/projects_mia/rel2_test/data/raw_data/rocmi_120618test1-IRMFonct_+perfusion-2018-06-12060428-05-T13DSENSE-T1TFE-000424_000.nii'], new value: ['/data/IRM/projects_mia/rel2_test/data/raw_data/alej170316_test24042018-IRMFonct_+perfusion-2016-03-17083444-00-T13DSENSE-T1TFE-000425_000.nii']
Traceback (most recent call last):
  File "/casa/home/.local/lib/python3.6/site-packages/traits/trait_notifiers.py", line 524, in _dispatch_change_event
    self.dispatch(handler, *args)
  File "/casa/home/.local/lib/python3.6/site-packages/traits/trait_notifiers.py", line 486, in dispatch
    handler(*args)
  File "/casa/host/build/python/soma/utils/functiontools.py", line 89, in __call__
    return self.func(*(self.args + args), **merged_kwargs)
  File "/casa/host/src/capsul/master/capsul/pipeline/pipeline_nodes.py", line 231, in _value_callback
    self.is_parameter_protected(source_plug_name))
  File "/casa/host/src/capsul/master/capsul/pipeline/pipeline_nodes.py", line 735, in set_plug_value
    self.process.set_parameter(plug_name, value, protected)
  File "/casa/host/src/capsul/master/capsul/process/process.py", line 1043, in set_parameter
    setattr(self, name, value)
  File "/casa/home/.local/lib/python3.6/site-packages/traits/trait_notifiers.py", line 478, in __call__
    self.notify_listener(self, object, trait_name, old, new)
  File "/casa/home/.local/lib/python3.6/site-packages/traits/trait_notifiers.py", line 561, in _notify_function_listener
    object, trait_name, old, new, self.handler
  File "/casa/home/.local/lib/python3.6/site-packages/traits/trait_notifiers.py", line 532, in _dispatch_change_event
    handle_exception(object, trait_name, old, new)
  File "/casa/home/.local/lib/python3.6/site-packages/traits/trait_notifiers.py", line 149, in _handle_exception
    raise excp
  File "/casa/home/.local/lib/python3.6/site-packages/traits/trait_notifiers.py", line 524, in _dispatch_change_event
    self.dispatch(handler, *args)
  File "/casa/home/.local/lib/python3.6/site-packages/traits/trait_notifiers.py", line 486, in dispatch
    handler(*args)
  File "/casa/host/build/python/soma/utils/functiontools.py", line 89, in __call__
    return self.func(*(self.args + args), **merged_kwargs)
  File "/casa/host/src/capsul/master/capsul/pipeline/pipeline_nodes.py", line 231, in _value_callback
    self.is_parameter_protected(source_plug_name))
  File "/casa/host/src/capsul/master/capsul/pipeline/pipeline_nodes.py", line 733, in set_plug_value
    elif is_trait_pathname(self.process.trait(plug_name)) and value is None:
  File "/casa/host/src/capsul/master/capsul/pipeline/pipeline_nodes.py", line 206, in process
    return get_ref(self._process)
  File "/casa/host/build/python/soma/utils/weak_proxy.py", line 51, in get_ref
    if isinstance(obj, weakref.ReferenceType):
ReferenceError: weakly-referenced object no longer exists
weakly-referenced object no longer exists
ERROR:traits:Exception occurred in traits notification handler for object: <mia_processes.bricks.preprocess.spm.spatial_preprocessing.Smooth object at 0x7f8b95c12bf8>, trait: in_files, old value: ['/data/IRM/projects_mia/rel2_test/data/raw_data/alej170316_test24042018-IRMFonct_+perfusion-2016-03-17083444-00-T13DSENSE-T1TFE-000425_000.nii'], new value: ['/data/IRM/projects_mia/rel2_test/data/raw_data/rocmi_120618test1-IRMFonct_+perfusion-2018-06-12060428-05-T13DSENSE-T1TFE-000424_000.nii']
Traceback (most recent call last):
  File "/casa/home/.local/lib/python3.6/site-packages/traits/trait_notifiers.py", line 524, in _dispatch_change_event
    self.dispatch(handler, *args)
  File "/casa/home/.local/lib/python3.6/site-packages/traits/trait_notifiers.py", line 486, in dispatch
    handler(*args)
  File "/casa/host/build/python/soma/utils/functiontools.py", line 89, in __call__
    return self.func(*(self.args + args), **merged_kwargs)
  File "/casa/host/src/capsul/master/capsul/pipeline/pipeline_nodes.py", line 231, in _value_callback
    self.is_parameter_protected(source_plug_name))
  File "/casa/host/src/capsul/master/capsul/pipeline/pipeline_nodes.py", line 733, in set_plug_value
    elif is_trait_pathname(self.process.trait(plug_name)) and value is None:
  File "/casa/host/src/capsul/master/capsul/pipeline/pipeline_nodes.py", line 206, in process
    return get_ref(self._process)
  File "/casa/host/build/python/soma/utils/weak_proxy.py", line 51, in get_ref
    if isinstance(obj, weakref.ReferenceType):
ReferenceError: weakly-referenced object no longer exists
ERROR:traits:Exception occurred in traits notification handler for object: <capsul.pipeline.pipeline.Pipeline object at 0x7f8bb210e360>, trait: in_files, old value: ['/data/IRM/projects_mia/rel2_test/data/raw_data/alej170316_test24042018-IRMFonct_+perfusion-2016-03-17083444-00-T13DSENSE-T1TFE-000425_000.nii'], new value: ['/data/IRM/projects_mia/rel2_test/data/raw_data/rocmi_120618test1-IRMFonct_+perfusion-2018-06-12060428-05-T13DSENSE-T1TFE-000424_000.nii']
Traceback (most recent call last):
  File "/casa/home/.local/lib/python3.6/site-packages/traits/trait_notifiers.py", line 524, in _dispatch_change_event
    self.dispatch(handler, *args)
  File "/casa/home/.local/lib/python3.6/site-packages/traits/trait_notifiers.py", line 486, in dispatch
    handler(*args)
  File "/casa/host/build/python/soma/utils/functiontools.py", line 89, in __call__
    return self.func(*(self.args + args), **merged_kwargs)
  File "/casa/host/src/capsul/master/capsul/pipeline/pipeline_nodes.py", line 231, in _value_callback
    self.is_parameter_protected(source_plug_name))
  File "/casa/host/src/capsul/master/capsul/pipeline/pipeline_nodes.py", line 735, in set_plug_value
    self.process.set_parameter(plug_name, value, protected)
  File "/casa/host/src/capsul/master/capsul/process/process.py", line 1043, in set_parameter
    setattr(self, name, value)
  File "/casa/home/.local/lib/python3.6/site-packages/traits/trait_notifiers.py", line 478, in __call__
    self.notify_listener(self, object, trait_name, old, new)
  File "/casa/home/.local/lib/python3.6/site-packages/traits/trait_notifiers.py", line 561, in _notify_function_listener
    object, trait_name, old, new, self.handler
  File "/casa/home/.local/lib/python3.6/site-packages/traits/trait_notifiers.py", line 532, in _dispatch_change_event
    handle_exception(object, trait_name, old, new)
  File "/casa/home/.local/lib/python3.6/site-packages/traits/trait_notifiers.py", line 149, in _handle_exception
    raise excp
  File "/casa/home/.local/lib/python3.6/site-packages/traits/trait_notifiers.py", line 524, in _dispatch_change_event
    self.dispatch(handler, *args)
  File "/casa/home/.local/lib/python3.6/site-packages/traits/trait_notifiers.py", line 486, in dispatch
    handler(*args)
  File "/casa/host/build/python/soma/utils/functiontools.py", line 89, in __call__
    return self.func(*(self.args + args), **merged_kwargs)
  File "/casa/host/src/capsul/master/capsul/pipeline/pipeline_nodes.py", line 231, in _value_callback
    self.is_parameter_protected(source_plug_name))
  File "/casa/host/src/capsul/master/capsul/pipeline/pipeline_nodes.py", line 733, in set_plug_value
    elif is_trait_pathname(self.process.trait(plug_name)) and value is None:
  File "/casa/host/src/capsul/master/capsul/pipeline/pipeline_nodes.py", line 206, in process
    return get_ref(self._process)
  File "/casa/host/build/python/soma/utils/weak_proxy.py", line 51, in get_ref
    if isinstance(obj, weakref.ReferenceType):
ReferenceError: weakly-referenced object no longer exists
weakly-referenced object no longer exists
- Pipeline initialising ...

Completion / workflow...
ERROR:traits:Exception occurred in traits notification handler for object: <mia_processes.bricks.preprocess.spm.spatial_preprocessing.Smooth object at 0x7f8b95c12bf8>, trait: spm_script_file, old value: /data/IRM/projects_mia/rel2_test/scripts/pyscript_smooth_47858d10-988a-40cd-8ca0-67057f9ddd9a.m, new value: /data/IRM/projects_mia/rel2_test/scripts/pyscript_smooth_a7d60f4e-8ed2-40eb-906f-a29131fe221d.m
Traceback (most recent call last):
  File "/casa/home/.local/lib/python3.6/site-packages/traits/trait_notifiers.py", line 524, in _dispatch_change_event
    self.dispatch(handler, *args)
  File "/casa/home/.local/lib/python3.6/site-packages/traits/trait_notifiers.py", line 486, in dispatch
    handler(*args)
  File "/casa/host/build/python/soma/utils/functiontools.py", line 89, in __call__
    return self.func(*(self.args + args), **merged_kwargs)
  File "/casa/host/src/capsul/master/capsul/pipeline/pipeline_nodes.py", line 231, in _value_callback
    self.is_parameter_protected(source_plug_name))
  File "/casa/host/src/capsul/master/capsul/pipeline/pipeline_nodes.py", line 733, in set_plug_value
    elif is_trait_pathname(self.process.trait(plug_name)) and value is None:
  File "/casa/host/src/capsul/master/capsul/pipeline/pipeline_nodes.py", line 206, in process
    return get_ref(self._process)
  File "/casa/host/build/python/soma/utils/weak_proxy.py", line 51, in get_ref
    if isinstance(obj, weakref.ReferenceType):
ReferenceError: weakly-referenced object no longer exists

Workflow done.

init time: 0.05649566650390625

```

**Comment by LStruber** [comment]
I also reproduced this issue:
The first error `AttributeError: 'PipelineManagerTab' object has no attribute 'get_current_pipeline'` seems to be simple to solve: in function `get_missing_mandatory_parameters` of `pipeline_manager_tab.py` `self.get_current_pipeline().pipeline_node` is called while it should certainly be `self.pipelineEditorTabs.get_current_pipeline().pipeline_node` as everywhere else in the file.

However, replacing by the good call does not solve the second point of the issue ! I didn't dig into it yet and I'm not sure if it is an issue in MIA or Capsul. I had already noticed in the past that sometimes (I can't remember a concrete case), nodes turn blue. Is there a rationale for that or this is never a normal behavior ?

**Comment by servoz** [comment]
You are right, thanks to your last commit e6da463, we don't have the first issue described in the first message of this ticket.

However we still observe the second exception:
```
ERROR:traits:Exception occurred in traits notification handler for object: <mia_processes.bricks.preprocess.spm.spatial_preprocessing.Smooth object at 0x7f5dc712c888>, trait: in_files, old value: <undefined>, new value: ['/data/IRM/projects_mia/rel2_test0/data/raw_data/alej170316-IRMFonct_+perfusion-2016-03-17083444-01-T13DSENSE-T1TFE-000425_000.nii']
Traceback (most recent call last):
  File "/casa/home/.local/lib/python3.6/site-packages/traits/trait_notifiers.py", line 524, in _dispatch_change_event
    self.dispatch(handler, *args)
  File "/casa/home/.local/lib/python3.6/site-packages/traits/trait_notifiers.py", line 486, in dispatch
    handler(*args)
  File "/casa/host/build/python/soma/utils/functiontools.py", line 89, in __call__
    return self.func(*(self.args + args), **merged_kwargs)
  File "/casa/host/src/capsul/master/capsul/pipeline/pipeline_nodes.py", line 231, in _value_callback
    self.is_parameter_protected(source_plug_name))
  File "/casa/host/src/capsul/master/capsul/pipeline/pipeline_nodes.py", line 733, in set_plug_value
    elif is_trait_pathname(self.process.trait(plug_name)) and value is None:
  File "/casa/host/src/capsul/master/capsul/pipeline/pipeline_nodes.py", line 206, in process
    return get_ref(self._process)
  File "/casa/host/build/python/soma/utils/weak_proxy.py", line 51, in get_ref
    if isinstance(obj, weakref.ReferenceType):
ReferenceError: weakly-referenced object no longer exists
ERROR:traits:Exception occurred in traits notification handler for object: <capsul.pipeline.pipeline.Pipeline object at 0x7f5de1abebf8>, trait: in_files, old value: <undefined>, new value: ['/data/IRM/projects_mia/rel2_test0/data/raw_data/alej170316-IRMFonct_+perfusion-2016-03-17083444-01-T13DSENSE-T1TFE-000425_000.nii']
Traceback (most recent call last):
  File "/casa/home/.local/lib/python3.6/site-packages/traits/trait_notifiers.py", line 524, in _dispatch_change_event
    self.dispatch(handler, *args)
  File "/casa/home/.local/lib/python3.6/site-packages/traits/trait_notifiers.py", line 486, in dispatch
    handler(*args)
  File "/casa/host/build/python/soma/utils/functiontools.py", line 89, in __call__
    return self.func(*(self.args + args), **merged_kwargs)
  File "/casa/host/src/capsul/master/capsul/pipeline/pipeline_nodes.py", line 231, in _value_callback
    self.is_parameter_protected(source_plug_name))
  File "/casa/host/src/capsul/master/capsul/pipeline/pipeline_nodes.py", line 735, in set_plug_value
    self.process.set_parameter(plug_name, value, protected)
  File "/casa/host/src/capsul/master/capsul/process/process.py", line 1043, in set_parameter
    setattr(self, name, value)
  File "/casa/home/.local/lib/python3.6/site-packages/traits/trait_notifiers.py", line 478, in __call__
    self.notify_listener(self, object, trait_name, old, new)
  File "/casa/home/.local/lib/python3.6/site-packages/traits/trait_notifiers.py", line 561, in _notify_function_listener
    object, trait_name, old, new, self.handler
  File "/casa/home/.local/lib/python3.6/site-packages/traits/trait_notifiers.py", line 532, in _dispatch_change_event
    handle_exception(object, trait_name, old, new)
  File "/casa/home/.local/lib/python3.6/site-packages/traits/trait_notifiers.py", line 149, in _handle_exception
    raise excp
  File "/casa/home/.local/lib/python3.6/site-packages/traits/trait_notifiers.py", line 524, in _dispatch_change_event
    self.dispatch(handler, *args)
  File "/casa/home/.local/lib/python3.6/site-packages/traits/trait_notifiers.py", line 486, in dispatch
    handler(*args)
  File "/casa/host/build/python/soma/utils/functiontools.py", line 89, in __call__
    return self.func(*(self.args + args), **merged_kwargs)
  File "/casa/host/src/capsul/master/capsul/pipeline/pipeline_nodes.py", line 231, in _value_callback
    self.is_parameter_protected(source_plug_name))
  File "/casa/host/src/capsul/master/capsul/pipeline/pipeline_nodes.py", line 733, in set_plug_value
    elif is_trait_pathname(self.process.trait(plug_name)) and value is None:
  File "/casa/host/src/capsul/master/capsul/pipeline/pipeline_nodes.py", line 206, in process
    return get_ref(self._process)
  File "/casa/host/build/python/soma/utils/weak_proxy.py", line 51, in get_ref
    if isinstance(obj, weakref.ReferenceType):
ReferenceError: weakly-referenced object no longer exists
weakly-referenced object no longer exists
```
@denisri , please, can you remind us what the blue color code for gnodes means?

I don't know if the issue comes from mia or capsul ...

Anyway, I'm running out of time right now and I set myself to work on tickets #236, #239 before #255. I'll come back on this ticket ASAP.

**Comment by denisri** [comment]
I can reproduce the problem.
The error fires even before clicking on "run": it happens first when we select the input from the filter, and only after a first failed run attempt, as you describe.
It seems to be an object which has been deleted, but notification callbacks still fire for it.

**Comment by denisri** [comment]
Here is a simpler test case that reproduces the problem:
```
from capsul.api import capsul_engine, Pipeline
ce = capsul_engine()
proc = ce.get_process_instance('nipype.interfaces.spm.Smooth')
pipeline = Pipeline()
pipeline.add_process('babar', proc)
pipeline.export_parameter('babar', 'in_files')
del pipeline
proc.in_files = ['/tmp/poupou.nii']
```
The nodes and connections are still living after the pipeline deletion, thus `proc.in_files = ...` fires a notification in the connected plugs, here the pipeline node, whose pipeline is dead.
So we must ensure the nodes are actually destroyed.
