### ISSUE TITLE
 [general purpose] UTs fail

### ISSUE THREAD

**Issue by servoz** [populse/populse_mia#307]
[The UT is currently down.](https://ci.appveyor.com/project/populse/populse-mia/builds/47429626)
There seems to be a link with sip.
```
Traceback (most recent call last):
  File "C:\projects\capsul\capsul\qt_gui\widgets\pipeline_developer_view.py", line 2693, in __del__
    self.release_pipeline(delete=True)
  File "C:\projects\capsul\capsul\qt_gui\widgets\pipeline_developer_view.py", line 2800, in release_pipeline
    from soma.qt_gui.qt_backend import sip
  File "C:\projects\soma-base\python\soma\qt_gui\qt_backend.py", line 83, in find_module
    found = imp.find_module(module_name, qt_module.__path__)
  File "C:\Python37\lib\imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named 'sip'
```

**Comment by denisri** [comment]
I have tried to fix it. Can you give it a try please ?

**Comment by servoz** [comment]
Sure! Thanks a lot Denis, your fix in soma is effective and the UTs in populse_mai are working properly again!
