### ISSUE TITLE
MIA crashes when click on check input / output files

### ISSUE THREAD

**Issue by servoz** [populse/populse_mia#36]
* popule_mia crash with exception:
```
Traceback (most recent call last):
  File "/home/econdami/Git_Projects/populse_mia/python/populse_mia/pipeline_manager/capsul_files/pipeline_developper_view.py", line 3033, in check_files
    self.scene.pipeline)
  File "/home/econdami/Git_Projects/populse_mia/python/populse_mia/pipeline_manager/capsul_files/pipeline_tools.py", line 633, in nodes_with_existing_outputs
    node_name, node = nodes.pop(0)
AttributeError: 'generator' object has no attribute 'pop'
```

# Minimal steps to reproduce:
1. Open populse_mia
2. On the Pipeline Manager tab, drag a brick (ex. the nipype smooth brick) onto an editor window 
3. Right click on the brick and choose check input / output files

**Comment by servoz** [comment]
Test for appveyor setting

**Comment by dhrbn** [comment]
The bug came from the "nodes" variable used in nodes_with_existing_outputs and nodes_with_missing_inputs. They used to be dict_items object and then a .pop() method was used on them, which cannot work with this kind of object. In https://github.com/populse/populse_mia/commit/cbfd4863ebee34549910daae7b65e922be025e44, I've just casted these dict_items to list objects and it seems to work.
