### ISSUE TITLE
Debug PipelineDevelopperView's "open node controller" action. Linked with #79

### ISSUE THREAD

**Issue by dhrbn** [populse/populse_mia#38]
This action has been disabled (python/populse_mia/pipeline_manager/capsul_files/pipeline_developper_view.py + controller_action.setDisabled(True)) for now because it caused bugs when tuples and lists are in the current node.

For instance, for a Nipype SPM Smooth node:

Traceback (most recent call last):
  File "/home/david/POPULSE/populse_mia/python/populse_mia/pipeline_manager/capsul_files/pipeline_developper_view.py", line 2620, in openProcessController
    process, enable_attr_from_filename=True, enable_load_buttons=True)
  File "/home/david/MyCAPSUL/capsul/capsul/qt_gui/widgets/attributed_process_widget.py", line 93, in __init__
    parent=param_widget)
  File "/home/david/soma_svn/soma-base/python/soma/qt_gui/controller_widget.py", line 87, in __init__
    controller, parent, name, live, hide_labels, select_controls)
  File "/home/david/soma_svn/soma-base/python/soma/qt_gui/controller_widget.py", line 210, in __init__
    self._create_controls()
  File "/home/david/soma_svn/soma-base/python/soma/qt_gui/controller_widget.py", line 513, in _create_controls
    self.create_control(trait_name, trait)
  File "/home/david/soma_svn/soma-base/python/soma/qt_gui/controller_widget.py", line 567, in create_control
    layout, group)
  File "/home/david/soma_svn/soma-base/python/soma/qt_gui/controller_widget.py", line 696, in _create_control_in_layout
    trait, label_class)
  File "/home/david/soma_svn/soma-base/python/soma/qt_gui/controls/List.py", line 169, in create_widget
    trait.handler.inner_traits()))
Exception: Expect only one inner trait in List control. Trait 'fwhm' inner trait is '()'.

**Comment by servoz** [comment]
I am reopening this issue because it seems that it was closed 2 days ago, as a side effect of the rewrite of the history, which I made in order to delete from the history the large files now followed by git-fs.
The first investigation I conducted seems to indicate that following this operation, some issues have been closed (which I will reopen after some checks). The integrity of the populse_mia project does not seems to have changed (I think the SHA-1 of the commits were changed during the operations, that could explain the side effect observed!)

**Comment by servoz** [comment]
Because I check all closed issue after rewriting the history, I notice that the crash is only observed with the nipype process and not with mine (example: a right click on the smooth brick of the nipype library raises the exceptions previously described by @dhrbn but not the smooth brick of my personal library. I didn't take any more time to think about this problem ... this is just a reminder)

**Comment by M40V** [comment]
https://github.com/populse/soma-base/commit/daadf5c109a8e87323ad10574523c954cc8fd29e
