### ISSUE TITLE
ModuleNotFoundError: No module named 'PyQt5.sip'

### ISSUE THREAD

**Issue by servoz** [populse/populse_mia#39]
Since the last update of the main.py (1bb78b9207),  there is a problem to launch mia:
% mia
Populse_MIA in "developer" mode
Traceback (most recent call last):
  File "main.py", line 310, in <module>
    main()
  File "main.py", line 296, in main
    verify_processes()
  File "main.py", line 122, in verify_processes
    from PyQt5.QtWidgets import QApplication
ModuleNotFoundError: No module named 'PyQt5.sip'

**Comment by servoz** [comment]
In fact, this is due to the pyqt5 installation during the python3 setup.py install for populse_mia. It seems that the pyqt5 installation hidden the pyqt5of my fedora distrib ... So, fixed by removing the pip3 installation of pyqt5: pip3 uninstall PyQt5
