### ISSUE TITLE
Already existing NIFTI data are not exported to mia from MriConverter

### ISSUE THREAD

**Issue by servoz** [populse/populse_mia#46]
With the latest version of MriConverter (18.1.7a), when the data is already in NIFTI format, no data is exported to mia.The work around is currently to use version 18.1.5a, which seems to not produce this bug.

At the same time the following exception are raised, that do not produce mia's crash and can be view as only warnings:

Traceback (most recent call last):
  File "main.py", line 238, in my_excepthook
    clean_up()
  File "main.py", line 34, in clean_up
    main_window.remove_raw_files_useless()
  File "/home/econdami/Git_Projects/populse_mia/python/populse_mia/main_window/main_window.py", line 328, in remove_raw_files_useless
    self.project.database.__exit__(None, None, None)
  File "/home/econdami/Git_Projects/populse_mia/python/populse_mia/project/database_mia.py", line 147, in __exit__
    current_session._populse_db_counter -= 1
AttributeError: 'Session' object has no attribute '_populse_db_counter'

Original exception was:
Traceback (most recent call last):
  File "/home/econdami/Git_Projects/populse_mia/python/populse_mia/project/controller.py", line 119, in run
    log_to_read = max(list_logs, key=os.path.getctime)
ValueError: max() arg is an empty sequence
excepthook
clean up done
Error in sys.excepthook:
Traceback (most recent call last):
  File "main.py", line 238, in my_excepthook
    clean_up()
  File "main.py", line 32, in clean_up
    opened_projects.remove(main_window.project.folder)
ValueError: list.remove(x): x not in list

Original exception was:
Traceback (most recent call last):
  File "/home/econdami/Git_Projects/populse_mia/python/populse_mia/main_window/main_window.py", line 863, in import_data
    new_scans = controller.read_log(self.project, self)
  File "/home/econdami/Git_Projects/populse_mia/python/populse_mia/project/controller.py", line 61, in read_log
    return main_window.progress.worker.scans_added
AttributeError: 'ImportWorker' object has no attribute 'scans_added'

**Comment by servoz** [comment]
This bug is fixed by the 18.1.8a version of the MriConverter
