### ISSUE TITLE
MIA crashes when right click on "open node controller". Linked with #38

### ISSUE THREAD

**Issue by servoz** [populse/populse_mia#79]
This is observed with the nipype library, not observed with  personal bricks (yet build from nipype library). 

* popule_mia crash with exception:
```
Traceback (most recent call last):
  File "/home/econdami/.local/lib/python3.6/site-packages/capsul-2.2.1-py3.6.egg/capsul/qt_gui/widgets/pipeline_developper_view.py", line 2770, in openProcessController
    process, enable_attr_from_filename=True, enable_load_buttons=True)
  File "/home/econdami/.local/lib/python3.6/site-packages/capsul-2.2.1-py3.6.egg/capsul/qt_gui/widgets/attributed_process_widget.py", line 93, in __init__
    parent=param_widget)
  File "/home/econdami/.local/lib/python3.6/site-packages/soma_base-4.6.4-py3.6.egg/soma/qt_gui/controller_widget.py", line 87, in __init__
    controller, parent, name, live, hide_labels, select_controls)
  File "/home/econdami/.local/lib/python3.6/site-packages/soma_base-4.6.4-py3.6.egg/soma/qt_gui/controller_widget.py", line 210, in __init__
    self._create_controls()
  File "/home/econdami/.local/lib/python3.6/site-packages/soma_base-4.6.4-py3.6.egg/soma/qt_gui/controller_widget.py", line 513, in _create_controls
    self.create_control(trait_name, trait)
  File "/home/econdami/.local/lib/python3.6/site-packages/soma_base-4.6.4-py3.6.egg/soma/qt_gui/controller_widget.py", line 567, in create_control
    layout, group)
  File "/home/econdami/.local/lib/python3.6/site-packages/soma_base-4.6.4-py3.6.egg/soma/qt_gui/controller_widget.py", line 696, in _create_control_in_layout
    trait, label_class)
  File "/home/econdami/.local/lib/python3.6/site-packages/soma_base-4.6.4-py3.6.egg/soma/qt_gui/controls/List.py", line 169, in create_widget
    trait.handler.inner_traits()))
Exception: Expect only one inner trait in List control. Trait 'fwhm' inner trait is '()'.
```
# Minimal steps to reproduce:
1. Open populse_mia
2. On the Pipeline Manager tab, drag a brick (ex. the nipype smooth brick) onto an editor window 
3. Right click on the brick and choose open node controller.

**Comment by servoz** [comment]
[A fix has been made in soma](https://github.com/populse/soma-base/issues/2). To be tested in populse_mia, then, if necessary, close this populse_mia problem (and the linked ticket)

**Comment by M40V** [comment]
https://github.com/populse/soma-base/commit/daadf5c109a8e87323ad10574523c954cc8fd29e
